@startuml Kino
class FilmManager {
    -List filmList
    +addFilm()
    +deleteFilm()
    +getFilmList()
}

class ScreeningRoomManager {
    -List roomsList
    +addScreeningRoom()
    +deleteScreeningRoom()
    +addFilmToRoom()
    +deleteFilmFromRoom()
    +getRoomsList()
}

class TicketManager {
    -List ticketList
    +addTicket()
    +removeTicket()
    +getTicketList()
}

class ScreeningRoom {
    -String name
    -int seats
    -int rowNumber
    -Screening screening
    -Date beginHour
}

class Film {
    -String title
    -int length
}

class Screening {
    -Time beginTime
    -Date screeningDate
    -Film film
    -ScreeningRoom screeningRoom
}

ScreeningRoom o-- Screening

abstract class Ticket {
    -float price
    -Film film
    -int rowNumber
    +calculatePrice()
}

Ticket --|> Student
Ticket --|> Group
Ticket --|> Normal

class Group {
    -int discount
    -int numberOfPeople
}

class Student {
    -int discount
    -int age
}

class Normal {

}


@enduml